### ISSUE TITLE
Are you planning to make the extension look and feel like the chromium media controls feature?

### ISSUE THREAD

**Issue by iGameEveryDay6** [igorlogius/tabs-media-controller#1]
I'd say that would be pretty neat. I wouldn't mind if it looks a bit Firefox-y.

**Comment by igorlogius** [comment]
Well the inital idea was to create something similar to chromiums media controls, but i never intened to copy chromiums design/look 1:1. 

So if you have a Firefox-y suggestion, feel free to let me know. :-)
