### ISSUE TITLE
Support for 163 music

### ISSUE THREAD

**Issue by xz-dev** [igorlogius/tabs-media-controller#2]
**Describe the bug**
I test it, it's working for bilibili, but not in 163 music which is a chinese music website.

**To Reproduce**
1. Go to https://music.163.com
2. Play anything
3. Nothing in addon panel

**Expected behavior**
Music player controller should show in panel.

**Screenshots**
nope.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: firefox-developer-edition 
 - Version: Mozilla Firefox 107.0b8

**Additional context**
nope

**Comment by igorlogius** [comment]
Seems like the sites uses an unattached HTMLMediaElement 
ref. https://stackoverflow.com/questions/41514612/detect-audio-element-not-added-to-dom
I am not sure if there is a way to get around this.
If not, then the only option i see would be to make a feature request to mozilla to add an API which lets one iterate MediaElements of a tab context.

**Comment by xz-dev** [comment]
But KDE can get the status, so Firefox must have some way get that.
![图片](https://user-images.githubusercontent.com/32761048/200123921-d86ed7fe-eabf-4ebc-8262-95620fba864c.png)

**Comment by igorlogius** [comment]
That seems to use the browser internal audio source api (most likely using pulseaudio sinks) 

That is sadly not available to addons. 
Everything that is available is 
[this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API)
which sadly is lacking a real media api. Sorry.

**Comment by igorlogius** [comment]
now works ... but it might not be the "best" or most stable solution ever.

![snip_20230502-202530](https://user-images.githubusercontent.com/67047467/235752947-81d0cfa1-313d-47ce-b6cf-50a1db8b5224.png)

**Comment by xz-dev** [comment]
Great, pls let me know how to donate you!

**Comment by igorlogius** [comment]
@xz-dev 

Very nice of you, but you do not need to donate!
