### ISSUE TITLE
background image alternative

### ISSUE THREAD

**Issue by toppits** [igorlogius/tabs-media-controller#4]
Hi, the background image feature is... interesting. But could you make an option to have the thumbnail/preview small or lose it completely?

**Comment by igorlogius** [comment]
>.> i rather not make individual change like that... but what i could see is make it that people can add their own CSS to re-style the popup in any way they like.

**Comment by igorlogius** [comment]
This should work

https://github.com/igorlogius/tabs-media-controller/assets/67047467/290c2109-cab9-4230-9547-83285f042b5c

**Comment by igorlogius** [comment]
Still have to create a sane default ... which isnt as easy (at least for me) ... so it might takea a little while ... or maybe someone whants to go nuts and propose something ... which would be totally fine by me, since i suck as CSS. :-)

**Comment by toppits** [comment]
no worries. Th extension isnt quite what i was looking for anyway, which is a way to jump to the tab thats playing audio

**Comment by igorlogius** [comment]
> jump to the tab thats playing audio

https://addons.mozilla.org/en-US/firefox/addon/switch-to-audible-tab
